import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--use-gl=angle','--use-angle=swiftshader','--no-sandbox'] });
const ctx = await b.newContext({ viewport:{width:390,height:844}, hasTouch:true, isMobile:true });
await ctx.addInitScript(()=>{try{localStorage.setItem('voidPlayed','1');localStorage.setItem('voidTut','1');}catch{}});
const p = await ctx.newPage();
await p.route('**/functions/v1/ingest-events',(r)=>r.fulfill({status:200,body:'{}'}));
const seen=[];
await p.route('**/assets/hf3d/**', (r)=>{ seen.push(r.request().url()); r.fulfill({status:404,body:''}); });
await p.goto('http://127.0.0.1:4177/?w=gameday',{waitUntil:'commit'});
await p.waitForFunction(()=>window.__matchState!=null,null,{timeout:200000});
await p.waitForTimeout(4000);
const u = seen.map(s=>s.split('/').pop());
const dup = u.filter((x,i)=>u.indexOf(x)!==i);
console.log(JSON.stringify({ total: seen.length, unique: [...new Set(u)] }));
await b.close();
